#!/bin/bash
#
# Slightly modified version of '/etc/update-motd.d/50-landscape-sysinfo'.
#
################################################################################

cores=$(grep -c ^processor /proc/cpuinfo 2>/dev/null)
[[ $cores = 0 ]] && cores=1
threshold="${cores:-1}.0"

echo ""
if [[ $(echo "$(cut -f1 -d ' ' /proc/loadavg) < $threshold" | bc) = 1 ]]; then
    python3 /etc/update-motd.d/sysinfo.py
else
    echo " System information disabled due to load higher than $threshold"
fi
echo ""
