#!/bin/bash

red=$'\033[1;31m'
nc=$'\033[0m'

if [[ -x /usr/sbin/needrestart ]]; then
    n=$(DEBIAN_FRONTEND=noninteractive echo "" | /usr/sbin/needrestart -k -v -n 2>/dev/null | grep -c "Pending kernel upgrade\!")
    if [[ $n -gt 0 ]]; then
        printf $red
        printf "  Pending kernel upgrade! "
        printf $nc
        printf "You should consider rebooting your machine.\n\n"
    fi
fi
